### ISSUE TITLE
Fetch Issues

### ISSUE THREAD

**Issue by sprintyaf** [vakhokoto/GithubExstension#19]
We need information about issues for our data analytics module. 
Somebody add get_issues method in [fetch.py ](https://github.com/vakhokoto/GithubExstension/blob/master/src/server/analytic/fetching/fetch.py) and also update [repository.py](https://github.com/vakhokoto/GithubExstension/blob/master/src/server/analytic/objects/repository.py)

**Comment by lkito** [comment]
I'd like to do this one

**Comment by sprintyaf** [comment]
> I'd like to do this one

Great!

**Comment by enqidu** [comment]
ახალი ეპიზოდი 😍😍🎆 -------> [CRY BABIES 💦 MAGIC TEARS ](https://www.youtube.com/watch?v=fmeRWNNlj2s)💕

**Comment by lkito** [comment]
ძაან მაინტერესებს, "ახალს" რას ეძახი. 16 ივნისსაა დადებული. მართლა ახალი გგონია? ნამდვილი ფანი რომ იყო, გეცოდინებოდა, რომ ეგ ეპიზოდი საერთოთ 2 დღით ადრე დაი-leak-ა cryx_baby ფორუმებზე, ასე რომ, ორჯერ უფრო ცდები. როგორ გრძნობ თავს? ბედნიერი ხარ? გაიხუმრე? სასაცილო იყო?

**Comment by enqidu** [comment]
მაპატიე

**Comment by sprintyaf** [comment]
#21
